sudo: required
language: python

matrix:
  fast_finish: true
  include:
    - {python: 3.6.10, env: TOXENV=py36-epolls-dnspython1}
    - {python: 3.6.10, env: TOXENV=py36-poll-dnspython1}
    - {python: 3.6.10, env: TOXENV=py36-selects-dnspython1}

    - {python: 3.6.10, env: TOXENV=py36-selects-dnspython2}

    - {python: 3.6.10, env: TOXENV=ipv6}

    - {python: 3.6.7, env: TOXENV=py36-epolls-dnspython1}
    - {python: 3.6.7, env: TOXENV=py36-poll-dnspython1}
    - {python: 3.6.7, env: TOXENV=py36-selects-dnspython1}

    - {python: 3.6.7, env: TOXENV=py36-selects-dnspython2}

    - {python: 3.6.7, env: TOXENV=ipv6}

cache:
  apt: true
  ccache: true
  pip: true
  directories:
    - $HOME/.cache
addons:
  apt_packages:
    - ccache
    - libffi-dev
    - libmysqlclient-dev
    - libpq-dev
    - libssl-dev
    - libzmq3-dev

install:
  - pip install --upgrade pip setuptools tox virtualenv codecov
before_script:
  - "export EVENTLET_DB_TEST_AUTH='{\"psycopg2\": {\"user\": \"postgres\"}, \"MySQLdb\": {\"passwd\": \"\", \"host\": \"localhost\", \"user\": \"root\"}}'"
  - "export PATH=/usr/lib/ccache:$PATH"
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6' ; fi
script:
  - tox -v -v
  - codecov --flags=$(echo $TOXENV |tr -d -- '-.')
after_failure:
  - for X in .tox/$TOXENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
  - echo "pip.log\n"; cat $HOME/.pip/pip.log

notifications:
  slack: eventlet-net:OYrQ1JE3hdTD78yQY1yZJnnc
